# blog.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy
  namespace: assignment2
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: db-service
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: password
          ports:
            - containerPort: 80
              name: wordpress

---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: assignment2
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: blog